
# A string specifying the project ID
project_id = "fwkgnukqwpamjaurigmk"

[api]
# Port number for the API
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage", "graphql_public"]

[db]
# Port number for the database
port = 54322

[studio]
# Port number for Supabase Studio
port = 54323

[inbucket]
# Port number for the email testing server
port = 54324

[auth]
# Enabled/disable JWT authentication
enable_signup = true

[storage]
# Enabled/disable storage API and services
file_size_limit = "50MiB"

# Function configuration
[functions]
# Function named get-secret
[functions.get_secret]
verify_jwt = false

# Function named company-research
[functions.company_research]
verify_jwt = false
